project:
  output-dir: out
  type: website
  render:
    - topcountries/index.qmd
    - scatter/index.qmd
    # - embed-bycountry.qmd
    # - embed-netflow-scatter.qmd
  resources:
    - /data/country-list.csv
    - /data/popular-origins-by-destination.csv
    - /data/popular-destinations-by-origin.csv
    - /data/netflow-ratios.csv
