---
title: "STUDENT FLOW BY COUNTRY"
subtitle: "WHERE DO STUDENTS COME FROM, AND WHERE DO THEY GO?"
page-layout: custom
theme: none
css:
  - style/embed.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css
  - style/modal.css
execute:
  echo: false
format:
  html:
    header-includes: |
      <!-- Global site tag (gtag.js) - Google Analytics (no cookies!) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-3E86R5NVXZ"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-3E86R5NVXZ', {
          client_storage: 'none'
        });
      </script>
---

```{ojs}
countryList =
  await FileAttachment("data/country-list.csv")
  .csv({ typed: true });

viewof basisSelect = Inputs.select(countryList.map(d => d.name), {
  label: "Country",
  sort: true,
  unqiue: true
});
viewof yearSelect = Inputs.range([1998, 2021], {step: 1, label: "Year"});
```

```{ojs}
//| output: false

// load the data run off from the analysis
popOrigins =
  await FileAttachment("data/popular-origins-by-destination.csv")
  .csv({ typed: true });
popDestinations =
  await FileAttachment("data/popular-destinations-by-origin.csv")
  .csv({ typed: true });

// first filter data by selected country
originByCountry = popOrigins.filter(function(row) {
  return row.dest_country_name == basisSelect;
});
destinationByCountry = popDestinations.filter(function(row) {
  return row.origin_country_name == basisSelect;
});

// compute a fixed x range for a given country across all years, in and out
countryMax = d3.max([
  d3.max(originByCountry, d => d.value_lumped),
  d3.max(destinationByCountry, d => d.value_lumped)
]);

// further filter data by selected year
filteredPopularOrigins = originByCountry.filter(function(row) {
  return row.year == yearSelect;
});
filteredPopularDestinations = destinationByCountry.filter(function(row) {
  return row.year == yearSelect;
});

commaFormat = d3.format(",.0f");
```

#### Where do ${basisSelect}'s foreign students come from? {.textcenter}

```{ojs}

popOriginPlot =
  filteredPopularOrigins.length == 0 ?
  html`<div style="width:100%;height:280px;padding-top:25px;display:flex;"><p style="margin:auto;">No data for student flows <strong>into ${basisSelect}</strong> in <strong>${yearSelect}</strong>.</p><div>` :
  Plot.plot({
    marks: [
      Plot.barX(filteredPopularOrigins, {
        y: "origin_country_lumped",
        x: "value_lumped",
        fill: "value_lumped",
        sort: {y: "x", reverse: true},
        ariaLabel: "origin_country_lumped",
        ariaDescription: d => `${d.origin_country_lumped} sent ${d.value_lumped} students.`,
        title: d => `${d.origin_country_lumped}: ${d.value_lumped} students`
      }),
      // label for value on left
      // Plot.text(filteredPopularOrigins, {
      //   y: "origin_country_lumped",
      //   x: "value_lumped",
      //   // add conditions to value label if required
      //   text: d => {
      //     if (d.cond_all == "----") { 
      //       commaFormat(d.value_lumped)
      //     } else {
      //       commaFormat(d.value_lumped) + " (" + d.cond_all + ")"
      //     }
      //   },
      //   dx: -25
      // }),
    ],
    x: {
      label: "Number of incoming students →",
      tickFormat: ".1s",
      ariaLabel: "X axis",
      ariaDescription: "Horizontal axis: number of incoming students, increasing to the right`",
      labelOffset: 45,
      domain: [0, countryMax]
    },
    y: {
      label: "",
      ariaLabel: "Y axis",
      ariaDescription: `Vertical axis: top 10 origin countries, ordered by popularity. All other origin countries sending students to ${basisSelect} are lumped together as 'other countries'`
    },
    color: { scheme: "ylgnbu", type: "sqrt" },
    width: 450,
    marginLeft: 175,
    marginRight: 65,
    marginBottom: 45,
    style: {
      fontFamily: "'Libre Franklin'",
      fontSize: "16px"
    }
  });
```
#### Where do ${basisSelect}'s students go? {.textcenter}

```{ojs}

popDestinationPlot = 
  filteredPopularDestinations.length == 0 ?
  html`<div style="width:100%;height:280px;padding-top:25px;display:flex;"><p style="margin:auto;">No data for student flows <strong>out of ${basisSelect}</strong> in <strong>${yearSelect}</strong>.</p><div>` :
  Plot.plot({
    marks: [
      Plot.barX(filteredPopularDestinations, {
        y: "dest_country_lumped",
        x: "value_lumped",
        fill: "value_lumped",
        sort: {y: "x", reverse: true},
        ariaLabel: "dest_country_lumped",
        ariaDescription: d => `${d.origin_country_lumped} received ${d.value_lumped} students.`,
        title: d => `${d.origin_country_lumped}: ${d.value_lumped} students`
      }),
      // label for value on right
      // Plot.text(filteredPopularDestinations, {
      //   y: "dest_country_lumped",
      //   x: "value_lumped",
      //   // add conditions to value label if required
      //   text: d => {
      //     if (d.cond_all == "----") { 
      //       commaFormat(d.value_lumped)
      //     } else {
      //       commaFormat(d.value_lumped) + " (" + d.cond_all + ")"
      //     }
      //   },
      //   dx: 25
      // })
    ],
    x: {
      label: "Number of outgoing students →",
      tickFormat: ".1s",
      ariaLabel: "X axis",
      ariaDescription: "Horizontal axis: number of outgoing students, increasing to the right",
      labelOffset: 45,
      domain: [0, countryMax]
    },
    y: {
      label: "",
      ariaLabel: "Y axis",
      ariaDescription: `Vertical axis: top 10 destination countries, ordered by popularity. All other destination countries receiving students from ${basisSelect} are lumped together as 'other countries'`
    },
    color: { scheme: "ylorrd", type: "sqrt" },
    width: 450,
    marginLeft: 175,
    marginRight: 65,
    marginBottom: 45,
    style: {
      fontFamily: "'Libre Franklin'",
      fontSize: "16px"
    }
  });
```

<!-- dialogs -->

```{ojs}
//| include: false

micro = require("micromodal@0.4.10")
micro.init({
  awaitOpenAnimation: true,
  awaitCloseAnimation: true
});
```

<!-- and here's the popup itself! -->

::: {.modalpanel}
<!-- dialog buttons -->
<a href="#" data-micromodal-trigger="modalnotes" tabindex="0">
  <i class="bi bi-clipboard-data"></i>
  Notes
</a>

<a href="#" data-micromodal-trigger="modaluseremix" tabindex="0">
  <i class="bi bi-share-fill"></i>
  Share
</a>

Chart: James Goldie, 360info. Data: UIS
:::

::::::: {#modaluseremix .modal .micromodal-slide aria-hidden="true"}
:::::: {.modal__overlay tabindex="-1" data-micromodal-close="true"}
::::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="modaluseremix-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

## Use + Remix

:::: {#modaluseremix-content}
These charts, as well as the analyses that underpin them, are available under a [**Creative Commons Attribution 4.0**](https://creativecommons.org/licenses/by/4.0) licence.

Please acknowledge [360info](https://360info.org) and [UIS](http://data.uis.unesco.org) when you use these charts and data.

#### Embed this chart in your story

Copy and paste the following code:

::: {.embedcode}
```
<iframe src="https://360info-studentflows.pages.dev/
embed-bycountry" title="Interactive charts showing the 
two-way flow of international students through a
selected country for a selected year." width="550"
height="850" scrolling="no" style="border:none;"></iframe>
```
:::

This content is subject to [360info's Terms of Use](https://newshub.360info.org/page/terms).

#### Get the data and code

Visit the [GitHub repository](https://github.com/360-info/report-global-education/tree/main/data) to:

* [**Download the data**](https://github.com/360-info/report-global-education/tree/main/data)
* [**Recreate or remix the chart**](https://github.com/360-info/report-global-education)
::::

:::::
::::::
:::::::

<!-- notes dialog -->

::::::: {#modalnotes .modal .micromodal-slide aria-hidden="true"}
:::::: {.modal__overlay tabindex="-1" data-micromodal-close="true"}
::::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="modalnotes-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
## Notes {#modalnotes-title}
</header>

:::: {#modalnotes-content}
This data was originally sourced from the [UNESCO Institute of Statistics](http://data.uis.unesco.org).

Some figures include nationally- or UNESCO-provided estimates, or have figures that have only been reported every few years.
::::

:::::
::::::
:::::::
